#
#
#
version: '3'


services:


  webserver_frontdoor:
    image: nginx:latest
    container_name: webserver_nginx_frontdoor
    networks:
      - webserver_webLAN
    volumes:
      - ./www_site_frontdoor:/www_site
      - ./site_frontdoor.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.backend=webserver_frontdoor"
      - "traefik.docker.network=webserver_webLAN"
      - "traefik.frontend.rule=Path:/"      
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"


  webserver_nginx:
    image: nginx:latest
    container_name: webserver_nginx
    #ports:
    #  - "8888:80"
    networks:
      - webserver_webLAN
    volumes:
      - ./www_site:/www_site
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - webserver_php
      - webserver_mysql
    labels:
      - "traefik.backend=webserver"
      - "traefik.docker.network=webserver_webLAN"
      #- "traefik.frontend.rule=PathPrefix:/yoloctf/;ReplacePathRegex: ^/yoloctf/(.*) /$$1"  
      - "traefik.frontend.rule=PathPrefix:/yoloctf/"      
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"


  webserver_php:
    #image: php:7-fpm
    build: php/.
    container_name: webserver_php
    env_file:
      - .env
    volumes:
      - ./www_site:/www_site
    networks:
      - webserver_webLAN
      - sqlLAN
    links:
      - webserver_mysql
    labels:
      - "traefik.enable=false"



  webserver_mysql:
    build: ./mysql/
    container_name: webserver_mysql
    # for debug
    #ports:
    #  - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
    networks:
        - sqlLAN
    labels:
      - "traefik.enable=false"


      
networks:
#  webLAN:
#    driver: bridge
  webserver_webLAN:
    external: true
  sqlLAN:
    driver: bridge